### ISSUE TITLE
wechat group invitation expired

### ISSUE THREAD

**Issue by boyugou** [iMeanAI/WebCanvas#17]
The wechat group QR code in the Readme has expired. Could you upload a new one?

**Comment by pan-2001** [comment]
You can add my personal WeChat account. Additionally, our work will be presented at the ICML TiFA and AMW workshop, we are looking forward to interacting with anyone interested in our research!
![mmqrcode1721703996709](https://github.com/user-attachments/assets/86de97e4-bc2d-4c27-ba13-9cf6403ff06d)
