### ISSUE TITLE
Can I use it in PC Software ?

### ISSUE THREAD

**Issue by LnYo-Cly** [iMeanAI/WebCanvas#31]

**Comment by pan-2001** [comment]
Could you please provide more details about your requirements?
Is your question: 'Can I integrate WebCanvas into PC software?' or 'Can I use WebCanvas to control PC software?'

**Comment by LnYo-Cly** [comment]
Can I use WebCanvas to control PC software?

**Comment by LnYo-Cly** [comment]
> Could you please provide more details about your requirements? Is your question: 'Can I integrate WebCanvas into PC software?' or 'Can I use WebCanvas to control PC software?'

Can I use WebCanvas to control PC software?
